<a href="https://colab.research.google.com/github/siriwat-heart/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

#Numpy Array

สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 แถว 3 หลัก 

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix transpose

In [8]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (Zeros,ones)

In [9]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix randoom

In [12]:
np.random.randn(5,5) # randoom เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[ 0.19700638, -0.39901675, -1.74436289, -1.64578838,  0.38127501],
       [ 1.88576668,  1.14240917, -0.88646709, -1.00164652, -0.55869639],
       [-2.21598744,  1.60082049,  2.42974464, -0.97163775, -0.98989753],
       [ 0.81891457,  0.86502473,  1.15531906,  0.17285606, -0.47481891],
       [-1.26250284, -1.66078049, -0.24271284, -0.83313671,  0.06621376]])

In [13]:
2 + (5*np.random.randn(3,3)) # randoom เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ 5.38932979,  0.88311948,  3.37288302],
       [16.40050309,  3.01713725,  7.76537826],
       [-1.80336434,  1.21366305, 10.0472909 ]])

In [14]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ระหว่าง [5,11) ขนาด (4,5)

array([[ 6,  7,  6,  8,  7],
       [ 6,  5, 10,  9, 10],
       [ 8, 10, 10,  7,  6],
       [ 6,  8,  9,  7,  9]])